id: IC45332A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:50:58+00:00'
last_modified: '2022-06-10T09:57:10.080093+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16214
  title: ལེགས་བཤད་འོད་དཀར་འཕྲེང་བ། ༼༡༤༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    641E:
      image_group_id: I1KG16248
      title: Volume 1 of legs bshad 'od dkar 'phreng ba/ (14)
      total_pages: 480
      order: 1
      base_file: 641E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
